pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    ratio-4x3-contain:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 768
                                    height: 576
                                    forceResize: true
                        medias:
                            '(max-width :576px)':
                                -
                                    method: contain
                                    arguments:
                                        width: 576
                                        height: 432
                                        forceResize: true
                        name: ratio-4x3-contain
                        description: ''
                        group: content
                        format: SOURCE
                        quality: 100
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1675247661
                        creationDate: 1669214030
                        preserveAnimation: false
