#parameters:
#    areablocks:
#        root:
#            Layout:
#                - 'section'
#            Slider:
#                - 'hero-bs-slider'
#        default:
#            Layout:
#                - 'section'
#            Content:
#                - 'heading'
#                - 'wysiwyg'