services:
    StarterkitAreasBundle\Document\Areabrick\Columns:
        arguments: [ '@Pimcore\Translation\Translator', '@parameter_bag' ]
        autowire: true
        tags:
            - { name: pimcore.area.brick, id: columns }

parameters:
    columns:
        rowClassStore:
            default:
                name: 'Standard'
                cssClass: ''
#            row-col-33:
#                name: '3 Spalten (1:1:1)'
#                cssClass: 'row-cols-2 row-cols-lg-3'
#            row-col-33-g3:
#                name: '3 Spalten (1:1:1) Gutter 3'
#                cssClass: 'row-cols-2 row-cols-lg-3 g-2 g-lg-3'

        columnsTypeStore:
            default:
                name: '1 Spalte'
                cols:
                    - 'col-12'
            col-50_50:
                name: '2 Spalten (1:1)'
                cols:
                    - 'col-12 col-lg-6'
                    - 'col-12 col-lg-6'
            col-33_66:
                name: '2 Spalten (2:1)'
                cols:
                    - 'col-12 col-lg-8'
                    - 'col-12 col-lg-4'
            col-66_33:
                name: '2 Spalten (1:2)'
                cols:
                    - 'col-12 col-lg-4'
                    - 'col-12 col-lg-8'
            col-25_75:
                name: '2 Spalten (3:1)'
                cols:
                    - 'col-12 col-lg-9'
                    - 'col-12 col-lg-3'
            col-75_25:
                name: '2 Spalten (1:3)'
                cols:
                    - 'col-12 col-lg-3'
                    - 'col-12 col-lg-9'
            col-33:
                name: '3 Spalten (1:1:1)'
                cols:
                    - 'col-12 col-lg-4'
                    - 'col-12 col-lg-4'
                    - 'col-12 col-lg-4'

###########################
## Area Section Options
###########################
#
#            exampleRow:
#                name: '3 Spalten (1:1:1) Gutter 3'
#                cssClass: 'row-cols-2 row-cols-lg-3 g-2 g-lg-3'

#            exampleCol:
#                name: '3 Spalten (1:1:1)'
#                customTamplate: 'col-6-3' // use filename only
#                attributes: 'data-jarallax data-speed=0.2'
#                cols:
#                    - 'col-12 col-lg-4'
#                    - 'col-12 col-lg-4'
#                    - 'col-12 col-lg-4'
