services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    StarterkitAreasBundle\Twig\Extension\TwigAreablock:
        tags: [ 'twig.extension' ]
        arguments:
            - '%areablocks%'

    StarterkitAreasBundle\Twig\Extension\TwigTests:
        tags: [ 'twig.extension' ]